name: Pipeline

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches:
      - "*"
    paths-ignore:
      - '**/README.md'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Enable pnpm
        run: corepack enable pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Install net-tools (for netstat)
        run: |
          sudo apt update -y
          sudo apt install -y net-tools

      - name: Run ESLint
        run: pnpm lint

      - name: Run tests with coverage
        run: pnpm tc

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
