name: Pipeline

on:
  push:
    branches:
      - pipeline-test
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches:
      - "*"
    paths-ignore:
      - '**/README.md'

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: comp1531/automarking:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      # - name: Run ESLint
      #   run: npm run lint

      - name: Run tests with coverage
        run: npm test start.test.ts

      # - name: Upload coverage reports to Codecov
      #   uses: codecov/codecov-action@v3
      #   env:
      #     CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}